### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by IvanFarkas** [excaliburpartners/hassio-addons#2]
# Getting started

## I need some help with OmniLink Bridge Add-on, please.

I have Hass.io running on a VM.
I installed OmniLink Bridge and after that MQTT broker.
The installation discovered my Omni, zones, controls, etc, but I do not see the devices in the devises list.

- What do I do to integrate Omni devices via OmniLink into Hass.io, please?
- Do I need to integrate MQTT?
- Is there a user manual?

Please find my config below.

```yaml
controller_address: [IP]
controller_port: [port]
controller_key1: [key1]
controller_key2: [key1]
controller_name: OmniLinkBridge
controller_name: OmniLinkBridge
time_sync: true
time_interval: 60
time_drift: 10
verbose_unhandled: true
verbose_event: true
verbose_area: true
verbose_zone: true
verbose_thermostat_timer: true
verbose_thermostat: true
verbose_unit: true
verbose_message: true
webapi_enabled: true
webapi_port: 8000
mqtt_enabled: true
mqtt_server: [IP from MQTT log]
mqtt_port: 1883
mqtt_username: [MQTT (Hass.io user) username]
mqtt_password: [MQTT (Hass.io user) password]
mqtt_prefix: omnilink
mqtt_discovery_prefix: hassio
mqtt_discovery_name_prefix: ''
mqtt_discovery_ignore_zones: ''
mqtt_discovery_ignore_units: ''
mqtt_discovery_override_zone: ''
notify_area: true
notify_message: true
mail_server: ''
mail_tls: false
mail_port: 25
mail_username: ''
mail_password: ''
mail_from: ''
mail_to: ''
prowl_key: ''
pushover_token: ''
pushover_user: ''
webapi_override_zone: ''
```

**Log**
[OmniLink_Bridge.log](https://github.com/excaliburpartners/hassio-addons/files/5978839/OmniLink_Bridge.log)
